### ISSUE TITLE
Support for External Node Packages in N8N

### ISSUE THREAD

**Issue by boemekeld** [Rbillon59/home-assistant-addons#112]
Hi @Rbillon59

First, thank you for this great work on N8N addon.

I'm wondering if there's support for using external Node.js packages within the addon. Besides setting the NODE_FUNCTION_ALLOW_EXTERNAL environment variable, we also need to install these external packages.

Enabling this feature would be very beneficial and useful, enhancing N8N's capabilities within Home Assistant.

Are there plans to support this?

Thanks!

**Comment by Rbillon59** [comment]
Hello !

Thank you !

I will need to do some tests on that to know how to tackle it. Do you have any experience with it ? Do you know if set the app will install and build packages on the fly ? Or does the plugin need to be installed beforehand ?

Thanks

**Comment by boemekeld** [comment]
Hi, I have the same question as you!

But I believe it will be necessary to install it first and then restart the container.

The best information I found about this is in this link:
https://community.n8n.io/t/websocket-n8n/40123

**Comment by Rbillon59** [comment]
Hello, I've added the feature. You just need to set the env var through the UI with the list of packages

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/1eef356f-283d-47d2-aaa0-a8179efb5e80">

<img width="480" alt="image" src="https://github.com/user-attachments/assets/6c95daf4-d8a7-4260-b928-a5bd430819a9">

Please feel free to update your n8n to the latest and let me know if everything is OK

**Comment by boemekeld** [comment]
Awesome! I'll test it now. Is the version still the same 1.0.48?

**Comment by Rbillon59** [comment]
Oh I just saw the version bump have been broken for a while on the config.json

I did a manual update, but I will take a look

The version with the feature is the 1.0.49

**Comment by boemekeld** [comment]
Thanks man, it worked!

**Comment by Rbillon59** [comment]
I fixed the version bump on the n8n repo, everything should be back to normal

Good ! I will close the issue.

Have a nice day 👋
